version: '3.6'
services:
  gpsutil:
    build:
      context: .
    restart: always
    ports:
      - "8081:8081"
    container_name: gpsutil
  rewardcentral:
    build:
      context: .
    restart: always
    ports:
      - "8082:8082"
    container_name: reward_central
  trippricer:
    build:
      context: .
    restart: always
    ports:
      - "8083:8083"
    container_name: trip_pricer
