version: '3.6'
services:
  tourguide:
    build:
      context: .
    networks:
      - microservice
    ports:
      - "8080:8080"
    container_name: tourguide
    depends_on:
      - gpsutilapi
      - rewardcentralapi
      - trippricerapi
  gpsutilapi:
    build:
      context: .
    networks:
      - microservice
    restart: always
    ports:
      - "8081:8081"
    container_name: gpsutilapi
  rewardcentralapi:
    build:
      context: .
    networks:
      - microservice
    restart: always
    ports:
      - "8082:8082"
    container_name: rewardcentralapi
  trippricerapi:
    build:
      context: .
    networks:
      - microservice
    restart: always
    ports:
      - "8083:8083"
    container_name: trippricerapi
networks:
  microservice:
