version: '3.6'
services:
  tourguide:
    build:
      context: .
    networks:
      - microservice
    ports:
      - "8080:8080"
    container_name: tourguide
    depends_on:
      - gpsutil
      - rewardcentral
      - trippricer
  gpsutil:
    build:
      context: .
    networks:
      - microservice
    restart: always
    ports:
      - "8081:8081"
    container_name: gpsutil
  rewardcentral:
    build:
      context: .
    networks:
      - microservice
    restart: always
    ports:
      - "8082:8082"
    container_name: rewardcentral
  trippricer:
    build:
      context: .
    networks:
      - microservice
    restart: always
    ports:
      - "8083:8083"
    container_name: trippricer
networks:
  microservice:
