version: '3.6'
services:
  tourguide:
    environment:
      - PROXY_GPSUTIL=gpsutil:8081
      - PROXY_REWARDCENTRAL=rewardcentral:8082
      - PROXY_TRIPPRICER=trippricer:8083
    build: tourguide
    image: tourguide-1.0.0.jar
    networks:
      - default
    ports:
      - "8080:8080"
    container_name: tourguide
    depends_on:
      - gpsutil
      - rewardcentral
      - trippricer
  gpsutil:
    build: gpsutil
    image: gpsapi-1.0.0.jar
    networks:
      - default
    restart: always
    ports:
      - "8081:8081"
    container_name: gpsutil
  rewardcentral:
    build: rewardcentral
    image: rewardcentralapi-1.0.0.jar
    networks:
      - default
    restart: always
    ports:
      - "8082:8082"
    container_name: rewardcentral
  trippricer:
    build: trippricer
    image: trippricerapi-1.0.0.jar
    networks:
      - default
    restart: always
    ports:
      - "8083:8083"
    container_name: trippricer

