version: '3.6'
services:
  tourguide:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - gpsutilapi
      - rewardcentralapi
      - trippricerapi
  gpsutilapi:
    build:
      context: .
    restart: always
    ports:
      - "8081:8081"
    container_name: gpsutil
  rewardcentralapi:
    build:
      context: .
    restart: always
    ports:
      - "8082:8082"
    container_name: reward_central
  trippricerapi:
    build:
      context: .
    restart: always
    ports:
      - "8083:8083"
    container_name: trip_pricer
